# Generated by Django 2.0 on 2021-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Image1',
            field=models.ImageField(default='abc', upload_to='imag/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='Image2',
            field=models.ImageField(default='abc', upload_to='imag/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='Roomno',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
