# Generated by Django 2.0 on 2021-08-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210828_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(default='abc', max_length=50)),
                ('Image', models.ImageField(upload_to='imag/')),
                ('Roomno', models.CharField(default='abc', max_length=50)),
                ('Rent', models.CharField(default='abc', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.House')),
            ],
        ),
    ]
