# Generated by Django 2.0 on 2021-09-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.BigIntegerField(default=123),
        ),
    ]
