# Generated by Django 2.0 on 2021-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Status',
            field=models.BigIntegerField(default=0),
        ),
    ]
